services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: node:22.11.0-alpine3.20
    restart: always
    command: sh -c 'npm i && npm run dev'
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
    - .env

  frontend:
    image: node:22.11.0-alpine3.20
    restart: always
    command: sh -c 'npm i && npm run dev'
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data: